apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels: 
    app: backend-restapp
    tier: backend
spec:
  #type:
  selector:
    app: backend-restapp
  ports: #List
    - name: http
      port: 8080 # ClusterIp Service Port
      targetPort: 8080